version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: dungeon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data"
    mem_limit: 512m
    cpus: 1

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dungeon
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: always
    mem_limit: 512m
    cpus: 1

  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: k6
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: always

  k6:
    image: grafana/k6:latest
    depends_on:
      - app
      - influxdb
    volumes:
      - ./stress/test.js:/scripts/test.js
    entrypoint: ["k6"]
    command:
      [
        "run",
        "--out",
        "influxdb=http://influxdb:8086/k6?consistency=one",
        "/scripts/test.js",
      ]

volumes:
  pgdata:
  influxdb-data:
