apiVersion: 1

datasources:
  - name: k6_influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: admin
    password: admin
    isDefault: true
    editable: true
