apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: ${TESTRUN_NAME}
  namespace: ${NAMESPACE}
spec:
  parallelism: ${PARALLELISM}
  script:
    configMap:
      name: ${CONFIGMAP_NAME}
      file: test.js
#__INFLUX_ARGS__
  runner:
    env:
      - name: TARGET_URL
        value: "${TARGET_URL}"
    resources:
      requests:
        cpu: "${REQ_CPU}"
        memory: "${REQ_MEM}"
      limits:
        cpu: "${LIM_CPU}"
        memory: "${LIM_MEM}"
